// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(ZipitContext))]
    partial class ZipitContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("API.Models.ConfirmCode", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("varchar(767)");

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.HasKey("Email");

                    b.ToTable("ConfirmCodes");
                });

            modelBuilder.Entity("API.Models.Listing", b =>
                {
                    b.Property<int>("ListingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ListingAvailability")
                        .HasColumnType("datetime");

                    b.Property<string>("ListingCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ListingCondition")
                        .HasColumnType("text");

                    b.Property<DateTime>("ListingDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ListingDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ListingImageURL")
                        .HasColumnType("text");

                    b.Property<int>("ListingPostCode")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<decimal>("ListingPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ListingTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ListingID");

                    b.HasIndex("UserID");

                    b.ToTable("Listings");

                    b.HasData(
                        new
                        {
                            ListingID = 1001,
                            ListingAvailability = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListingCategory = "Test Products",
                            ListingCondition = "Good",
                            ListingDate = new DateTime(2021, 10, 25, 21, 41, 49, 477, DateTimeKind.Utc).AddTicks(9308),
                            ListingDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ListingImageURL = "https://picsum.photos/100?random=1",
                            ListingPostCode = 2650,
                            ListingPrice = 1.00m,
                            ListingTitle = "Test Product 1",
                            ListingType = "Product",
                            UserID = 1
                        },
                        new
                        {
                            ListingID = 1002,
                            ListingAvailability = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListingCategory = "Test Products",
                            ListingCondition = "Great",
                            ListingDate = new DateTime(2021, 10, 25, 21, 41, 49, 478, DateTimeKind.Utc).AddTicks(915),
                            ListingDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ListingImageURL = "https://picsum.photos/100?random=2",
                            ListingPostCode = 4000,
                            ListingPrice = 2.00m,
                            ListingTitle = "Test Product 2",
                            ListingType = "Product",
                            UserID = 1
                        },
                        new
                        {
                            ListingID = 1003,
                            ListingAvailability = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListingCategory = "Test Products",
                            ListingCondition = "Needs Repair",
                            ListingDate = new DateTime(2021, 10, 25, 21, 41, 49, 478, DateTimeKind.Utc).AddTicks(918),
                            ListingDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ListingImageURL = "https://picsum.photos/100?random=3",
                            ListingPostCode = 2222,
                            ListingPrice = 3.00m,
                            ListingTitle = "Test Product 3",
                            ListingType = "Product",
                            UserID = 1
                        },
                        new
                        {
                            ListingID = 1004,
                            ListingAvailability = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListingCategory = "Test Products",
                            ListingCondition = "Fair",
                            ListingDate = new DateTime(2021, 10, 25, 21, 41, 49, 478, DateTimeKind.Utc).AddTicks(920),
                            ListingDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ListingImageURL = "https://picsum.photos/100?random=4",
                            ListingPostCode = 3232,
                            ListingPrice = 4.44m,
                            ListingTitle = "Test Product 4",
                            ListingType = "Product",
                            UserID = 1
                        },
                        new
                        {
                            ListingID = 1005,
                            ListingAvailability = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ListingCategory = "Test Products",
                            ListingCondition = "Excellent",
                            ListingDate = new DateTime(2021, 10, 25, 21, 41, 49, 478, DateTimeKind.Utc).AddTicks(921),
                            ListingDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ListingImageURL = "https://picsum.photos/100?random=5",
                            ListingPostCode = 4154,
                            ListingPrice = 5.0m,
                            ListingTitle = "Test Product 5",
                            ListingType = "Product",
                            UserID = 1
                        },
                        new
                        {
                            ListingID = 1006,
                            ListingAvailability = new DateTime(2021, 10, 25, 21, 41, 49, 478, DateTimeKind.Utc).AddTicks(922),
                            ListingCategory = "Test Services",
                            ListingDate = new DateTime(2021, 10, 25, 21, 41, 49, 478, DateTimeKind.Utc).AddTicks(922),
                            ListingDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ListingImageURL = "https://picsum.photos/100?random=1",
                            ListingPostCode = 4000,
                            ListingPrice = 6.0m,
                            ListingTitle = "Test Service 1",
                            ListingType = "Service",
                            UserID = 1
                        },
                        new
                        {
                            ListingID = 1007,
                            ListingAvailability = new DateTime(2021, 10, 25, 21, 41, 49, 478, DateTimeKind.Utc).AddTicks(1161),
                            ListingCategory = "Test Services",
                            ListingDate = new DateTime(2021, 10, 25, 21, 41, 49, 478, DateTimeKind.Utc).AddTicks(1160),
                            ListingDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ListingImageURL = "https://picsum.photos/100?random=2",
                            ListingPostCode = 3456,
                            ListingPrice = 7.0m,
                            ListingTitle = "Test Service 2",
                            ListingType = "Service",
                            UserID = 1
                        },
                        new
                        {
                            ListingID = 1008,
                            ListingAvailability = new DateTime(2021, 10, 25, 21, 41, 49, 478, DateTimeKind.Utc).AddTicks(1162),
                            ListingCategory = "Test Services",
                            ListingDate = new DateTime(2021, 10, 25, 21, 41, 49, 478, DateTimeKind.Utc).AddTicks(1162),
                            ListingDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ListingImageURL = "https://picsum.photos/100?random=3",
                            ListingPostCode = 2560,
                            ListingPrice = 8.89m,
                            ListingTitle = "Test Service 3",
                            ListingType = "Service",
                            UserID = 1
                        },
                        new
                        {
                            ListingID = 1009,
                            ListingAvailability = new DateTime(2021, 10, 25, 21, 41, 49, 478, DateTimeKind.Utc).AddTicks(1164),
                            ListingCategory = "Test Services",
                            ListingDate = new DateTime(2021, 10, 25, 21, 41, 49, 478, DateTimeKind.Utc).AddTicks(1163),
                            ListingDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ListingImageURL = "https://picsum.photos/100?random=4",
                            ListingPostCode = 3000,
                            ListingPrice = 8.89m,
                            ListingTitle = "Test Service 4",
                            ListingType = "Service",
                            UserID = 1
                        },
                        new
                        {
                            ListingID = 1010,
                            ListingAvailability = new DateTime(2021, 10, 25, 21, 41, 49, 478, DateTimeKind.Utc).AddTicks(1165),
                            ListingCategory = "Test Services",
                            ListingDate = new DateTime(2021, 10, 25, 21, 41, 49, 478, DateTimeKind.Utc).AddTicks(1165),
                            ListingDescription = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.",
                            ListingImageURL = "https://picsum.photos/100?random=5",
                            ListingPostCode = 4000,
                            ListingPrice = 10.99m,
                            ListingTitle = "Test Service 5",
                            ListingType = "Service",
                            UserID = 1
                        });
                });

            modelBuilder.Entity("API.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "User"
                        });
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("UserCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("varchar(767)");

                    b.Property<bool>("UserEmailVerfied")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("UserPasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserPostCode")
                        .HasMaxLength(4)
                        .HasColumnType("int");

                    b.Property<string>("UserState")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("varchar(3)");

                    b.Property<string>("UserStreet")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserID");

                    b.HasIndex("RoleID");

                    b.HasIndex("UserEmail")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("API.Models.Listing", b =>
                {
                    b.HasOne("API.Models.User", "User")
                        .WithMany("Listings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.HasOne("API.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("API.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Navigation("Listings");
                });
#pragma warning restore 612, 618
        }
    }
}
